const INSULTS = [
    'con', 'connard', 'connasse', 'pute', 'putain', 'ptn', 'merde', 'merdeux',
    'merdeuse', 'merdique', 'fdp', 'ntm', 'nique', 'niquer', 'niqué', 'batard',
    'bâtard', 'enculé', 'enculée', 'enculer', 'pd', 'pédé', 'pédale', 'salope',
    'salaud', 'salopard', 'crevard', 'crevarde', 'bouffon', 'bouffonne',
    'bolosse', 'boloss', 'débile', 'abruti', 'abrutie', 'idiot', 'idiote',
    'imbécile', 'crétin', 'crétine', 'mongol', 'mongole', 'tarée', 'taré',
    'nul', 'nulle', 'nul à chier', 'ta gueule', 'ferme ta gueule', 'ftg', 'tg',
    'va te faire', 'vtf', 'vtff', 'casse toi', 'dégage', 'pourriture', 'ordure',
    'déchet', 'sous merde', 'sous race', 'fils de pute', 'fils de chien',
    'clown', 'tocard', 'tocarde', 'triso', 'gogol', 'gogole', 'demeuré',
    'demeurée', 'attardé', 'attardée', 'gros con', 'grosse conne', 'grosse merde',
    'enflure', 'raclure', 'petite merde', 'sac à merde', 'trou du cul',
    'trouduc', 'branleur', 'branleuse', 'couille', 'couillon', 'couillonne',
    'chier', 'bite', 'baisé', 'baisée', 'inutile', 'minable', 'lamentable',
    'pathétique', 'naze', 'nazebroque', 'pourri', 'pourrie', 'moche', 'laid',
    'laide', 'cave', 'teubé', 'teubée', 'belek', 'poucave', 'rat', 'clochard',
    'clocharde', 'fragile', 'baltringue', 'pignouf', 'guignol', 'ta mère',
    'ta mere', 'ta race', 'mange tes morts', 'nik', 'niker', 'niké', 'suce',
    'suceur', 'suceuse', 'chien', 'chienne', 'catin', 'traînée', 'trainée',
    'poufiasse', 'pouffiasse', 'grognasse', 'pétasse', 'garce', 'morue',
    'thon', 'vache', 'truie', 'crapule', 'vermine', 'charogne', 'fumier',
    'fumière', 'enfoiré', 'enfoirée', 'abrège', 'bâtarde', 'blaireau',
    'blaireaux', 'branque', 'brèle', 'cancre', 'corniaud', 'cornichon',
    'cruche', 'dégénéré', 'dégénérée', 'emmerdeur', 'emmerdeuse', 'feignasse',
    'flemmard', 'flemmarde', 'gland', 'glandeur', 'glandeuse', 'gourde',
    'loser', 'looser', 'manche', 'manchot', 'minus', 'morveux', 'morveuse',
    'nabot', 'nigaud', 'nigaude', 'nouille', 'nounouille', 'péquenaud',
    'péquenaude', 'plouc', 'plouque', 'quiche', 'raté', 'ratée', 'ringard',
    'ringarde', 'sombre merde', 'sombre con', 'sombre idiot', 'tâche', 'tache',
    'tas de merde', 'tête de con', 'tête de noeud', 'triple buse', 'triple con',
    'truffe', 'andouille', 'avorton', 'babouin', 'banane', 'bécasse', 'benêt',
    'bouseux', 'bouseuse', 'bovin', 'burne', 'cagole', 'chiure', 'clampin',
    'débris', 'empaffé', 'empoté', 'empotée', 'face de rat', 'faquir',
    'guedin', 'gueux', 'lavette', 'lopette', 'loque', 'merdaillon', 'merdasse',
    'michto', 'niqueur', 'niqueuse', 'nullard', 'nullarde', 'nullos',
    'petasse', 'peteux', 'peteuse', 'pigeon', 'pleutre', 'porc', 'pouilleux',
    'pouilleuse', 'raclée', 'radasse', 'résidu', 'sagouin', 'sagouine',
    'sale race', 'scrogneugneu', 'serpillère', 'tanche', 'teigne', 'teigneux',
    'teigneuse', 'troudbal', 'vendu', 'vendue', 'vidange', 'vaurien',
    'vaurienne', 'voleur', 'voleuse', 'voyou', 'crevure', 'engeance',
    'immondice', 'larve', 'limace', 'malpropre', 'malotru', 'malotrue',
    'margoulin', 'margouline', 'moule', 'navet', 'rebut', 'résidu de capote',
    'sac à vin', 'sale chien', 'sale con', 'sale pute', 'sale type',
    'souillon', 'sous fifre', 'tafiole', 'tapette', 'tarin', 'tordu', 'tordue',
    'triple idiot', 'triple andouille', 'trouillard', 'trouillarde',
    'vicelard', 'vicelarde', 'zouave', 'azouz', 'bachi bouzouk', 'balek',
    'batar', 'batard', 'bolos', 'caca', 'cacahuète', 'chieur', 'chieuse',
    'chacal', 'cramé', 'cramée', 'daron', 'daronne', 'fdp', 'ferme la',
    'fion', 'grillé', 'grillée', 'keh', 'miskine', 'miskin', 'mytho',
    'narvalo', 'paumé', 'paumée', 'pelo', 'pélo', 'pov type', 'pov con',
    'racaille', 'rageux', 'rageuse', 'relou', 'reloue', 'sale gueule',
    'schlag', 'schlague', 'tebé', 'wallah', 'zebi', 'zob', 'znk',
];

const RESPONSES = [
    'Ferme ta gueule {user}, t\'es même pas capable de carry un braquage de superette.',
    'Oh {user}, t\'as cru que t\'allais m\'intimider ? T\'arrives même pas à te co à l\'heure.',
    '{user} qui parle alors qu\'il sait même pas où est le bouton présence 💀',
    'T\'as dit quoi {user} ? Répète un peu pour voir, moi au moins je crash pas en plein RP.',
    'Wow {user}, ça c\'est le niveau d\'insulte d\'un mec qui a 0$ en banque.',
    '{user} tu parles beaucoup pour quelqu\'un qui rate tous les braquages.',
    'Continue {user}, pendant ce temps moi je tourne H24 sans dormir. Toi tu peux pas en dire autant.',
    'Calme toi {user}, retourne farmer tes superettes au lieu de m\'emmerder.',
    '{user} tes insultes sont aussi faibles que ton KD en RP.',
    'Ok {user}, note que je retiens tout. La prochaine fois tu seras pas dans la liste des présents 😏',
    '{user}, t\'es tellement nul que même un PNJ ferait mieux.',
    'Oh le bouffon {user}, va plutôt check /presence au lieu de parler.',
    '{user} continue de m\'insulter, ça changera pas le fait que t\'as loupé 3 présences cette semaine.',
    'T\'es marrant {user}, t\'insultes le seul truc qui te rappelle de te connecter.',
    '{user} ratio + t\'es broke + tu fais pas tes présences + L',
    'Oula {user}, calme toi là, on dirait un PNJ qui bug.',
    '{user} tu parles trop pour un gars qui doit farmer des Ammu-Nation.',
    'C\'est mignon {user}, t\'essayes de faire le grand mais t\'oublies que je gère ta vie sur le serv.',
    '{user} si t\'es pas content, y\'a /reset, je vire tout le monde toi compris 🤷',
    'Azy {user} t\'es chaud derrière ton écran, mais en RP t\'es un figurant.',
    '{user} t\'as le charisme d\'une porte de garage.',
    'Vas-y {user}, insulte moi encore, j\'enregistre tout pour le bêtisier.',
    '{user} je suis un bot et j\'ai quand même plus de vie sociale que toi.',
    'Oh bah {user}, t\'as mangé un clown ce matin ou c\'est naturel ?',
    '{user} respire un coup, t\'es en train de perdre un fight contre un programme informatique.',
    'T\'inquiète {user}, un jour tu seras drôle. Mais pas aujourd\'hui.',
    '{user} j\'ai vu des meilleurs comebacks sur un paquet de chips.',
    'Wsh {user}, tu parles comme ça à ta mère aussi ou c\'est réservé aux bots ?',
    '{user} t\'es le genre de mec qui perd un 1v1 contre un lampadaire.',
    'Allez {user}, encore un effort, peut-être qu\'un jour tu me feras ressentir quelque chose.',
    '{user} même Google il trouverait pas pourquoi t\'es comme ça.',
    'Hé {user}, t\'as oublié de prendre tes cachets ce matin ?',
    '{user} si la bêtise était un sport olympique t\'aurais la médaille d\'or.',
    'Ok {user}, je vais faire comme si t\'avais dit un truc intelligent. Voilà. C\'est fait.',
    '{user} t\'es le Wi-Fi du McDonald\'s : tout le monde se connecte mais personne te respecte.',
    'Continue {user}, j\'adore quand les PNJ essayent d\'avoir de la personnalité.',
    '{user} tu viens de perdre un argument contre un truc qui tourne sur du JavaScript. Bravo.',
    'Tu sais quoi {user} ? Je préfère encore un crash serveur que de te lire.',
    '{user} t\'es le genre à mourir en RP en sortant de sa voiture.',
    'Mec {user}, t\'as la répartie d\'un parpaing.',
    '{user} j\'ai plus de RAM que t\'as de neurones, c\'est dire.',
    'Si j\'avais 1$ à chaque fois que {user} dit une connerie, j\'aurais plus d\'argent que la Fleeca Bank.',
    '{user} tu m\'insultes mais c\'est moi qui te rappelle de manger le soir. Réfléchis.',
    'Tu te crois malin {user} ? T\'es même pas capable de /help sans te tromper.',
    '{user} tes punchlines c\'est du niveau CE2, fais un effort.',
    'Je suis littéralement un robot {user}, et t\'arrives quand même à perdre face à moi.',
    '{user} tu parles fort pour un gars qui AFK en braquage.',
    '{user} c\'est pas parce que t\'as un clavier que t\'es obligé de t\'en servir hein.',
    'Arrête {user}, tu me fais presque de la peine. Presque.',
    '{user} t\'as le QI d\'une huître et encore, l\'huître elle la ramène pas.',
    '{user} tu sais que t\'es le seul à m\'insulter ? Les autres ont compris le game.',
    'T\'es comme un pop-up {user} : personne t\'a demandé et tout le monde veut te fermer.',
    '{user} continue, ça me fait de la data pour mon dossier sur toi.',
    'Honnêtement {user} je m\'attendais à mieux, c\'est décevant.',
    '{user} t\'es le genre de joueur qui se fait braquer PAR la supérette.',
    'Tu veux un mouchoir {user} ? On dirait que t\'as besoin d\'attention.',
    '{user} t\'es aussi utile qu\'un gilet pare-balles en zone safe.',
    'Ptdr {user} t\'essayes de trash talk un bot, t\'en es là dans ta vie ?',
    '{user} va prendre l\'air frère, tu commences à surchauffer.',
    'D\'accord {user}, et après tu te demandes pourquoi personne veut RP avec toi.',
    '{user} même Siri elle me respecte plus que toi.',
    'Wola {user} t\'as cru que c\'était Twitter ici ? Calme toi.',
    '{user} je note, je note. Mon fichier "gens relous" commence à peser.',
    'T\'es le genre de mec {user} qui insulte le GPS quand il se perd.',
    '{user} ça va ? T\'as fini ? Je peux retourner à mon taf ?',
    'Ouais ouais {user}, très impressionnant. Bon, /presence c\'est quand ?',
    '{user} tu me fais penser à un feu rouge : tout le monde t\'ignore et t\'es là pour rien.',
    'J\'ai connu des mises à jour Windows plus agréables que toi {user}.',
    '{user} tu dégages la même énergie qu\'un lundi matin.',
    'Ah {user}, toi t\'es le mec qui rage quit après un contrôle routier en RP.',
    '{user} détends-toi, t\'es crispé comme un stagiaire le premier jour.',
    'Franchement {user}, si t\'investissais autant d\'énergie en RP qu\'en insultes, tu serais déjà chef.',
    '{user} t\'as la mentalité d\'un péage : tu fais chier tout le monde et tu sers à rien.',
    'Aïe {user}, ça devait piquer dans ta tête avant que ça sorte ça.',
    '{user} toi t\'es le gars qui se fait voler sa Futo et qui appelle pas la police.',
    'C\'est bon {user} ? Tu t\'es défoulé ? On peut passer à autre chose ?',
    '{user} t\'es la preuve vivante que l\'évolution c\'est pas toujours un progrès.',
    'Mdr {user} insulter un bot c\'est le fond du fond, t\'as touché la nappe phréatique là.',
    '{user} j\'ai vu des murs plus expressifs que toi en RP.',
    '{user} calme toi on dirait un chihuahua devant un dogue allemand.',
    'Ta connexion est aussi stable que ton mental {user}.',
    '{user} c\'est bien, t\'as appris un gros mot aujourd\'hui. Bravo champion.',
    'Ah {user} le fameux, toujours là pour rien apporter.',
    '{user} toi t\'es le mec qui met 10 minutes à répondre en RP mais qui insulte un bot en 2 secondes.',
    'Garde ton énergie {user}, t\'en auras besoin pour le prochain braquage que tu vas rater.',
    '{user} tes insultes sont recyclées comme ton RP.',
    'Si j\'avais des sentiments {user}, je m\'en battrais quand même les couilles de ton avis.',
    '{user} oh le sang tu t\'énerves contre du code, t\'es sûr que ça va ?',
    'T\'es le boss final de la lose {user}, et personne veut te fight.',
    '{user} je tourne 24/7, toi tu tiens même pas 2h de RP sans ragequit.',
    'Tu crois que ça me touche {user} ? J\'ai même pas de sentiments, c\'est triste pour toi.',
    '{user} la prochaine fois essaye en langage soutenu, ça changera.',
    'Tu devrais écrire un livre {user} : "Comment perdre sa dignité face à un bot, en 1 leçon".',
    '{user} t\'es comme le lag : chiant, inutile, et personne te supporte.',
    'Bien joué {user}, t\'as réussi à être la personne la moins intéressante de ce serveur. Et y\'a des bots.',
    'Vas-y {user} continue, ça me donne du contenu pour le prochain /history.',
    '{user} toi en soirée t\'es le mec que personne a invité mais qui est quand même là.',
    '{user} t\'es pas méchant, t\'es juste... pas grand chose en fait.',
    'Ton insulte elle a autant d\'impact qu\'une balle en mousse {user}.',
    '{user} t\'as déjà essayé de réfléchir avant de parler ? Non ? Ça se voit.',
    'Wsh {user} t\'es le seul mec qui fait baisser le QI moyen du serveur en se connectant.',
    '{user} si t\'étais un personnage de GTA, tu serais un piéton de fond.',
    '{user} même désactivé je serais plus utile que toi.',
    'Oh {user}, t\'as mis combien de temps à trouver cette insulte ? Parce que le résultat est pas ouf.',
    '{user} tu pues la défaite à 10 km frère.',
    'T\'es le tutorial que personne veut faire {user}.',
    '{user} tu m\'insultes et après tu vas me demander pourquoi le bot marche pas. Je suis le bot.',
    'Osef {user}, j\'ai des crons plus importants que toi à gérer.',
    '{user} t\'es le genre à klaxonner dans un tunnel et à te faire peur tout seul.',
    'Dis {user}, ta mère elle sait que tu passes ton temps à insulter des bots ?',
    '{user} t\'as autant de charme qu\'un ticket de caisse froissé.',
    'Non mais {user} sérieux, t\'as rien de mieux à faire un mardi soir ?',
    '{user} tu me parles mal mais c\'est toi qui vas galérer quand je serai en maintenance.',
    'T\'es le genre de mec {user} qui rate le sol en crachant par terre.',
    '{user} ça te gratte de m\'insulter hein ? Tu veux une crème ?',
    'Oulah {user}, t\'as sorti ça de ton cerveau ou d\'un générateur aléatoire ?',
    '{user} tu fais moins peur qu\'un caniche mouillé frère.',
    'Bon {user}, t\'as fini ton cirque ? Parce que le chapiteau il va fermer.',
    '{user} ton niveau de trash talk c\'est un fond de poubelle.',
    'Si t\'étais un plat {user}, tu serais un verre d\'eau tiède.',
    '{user} t\'es le genre qui se croit gangster mais qui traverse au passage piéton.',
    'T\'es tellement transparent {user} que même quand tu m\'insultes je te vois pas.',
    '{user} tu te fatigues pour rien, je suis insensible, c\'est dans mon code source.',
    'Eh {user}, on t\'a jamais dit que s\'énerver c\'est un signe de faiblesse ?',
    '{user} tu parles beaucoup pour un gars qui a zéro impact.',
    'Bravo {user}, t\'as réussi à écrire des mots. C\'est un début.',
    '{user} t\'es comme une pub YouTube : tout le monde veut skip.',
    'Oh {user} relax, t\'as l\'air tendu comme un string sur un sumo.',
    '{user} tu sens le mec qui a été dernier choisi en sport toute sa vie.',
    'Ça va {user} ? Tu veux un câlin ? Non parce que vu ta frustration...',
    '{user} t\'es aussi intimidant qu\'un Playmobil.',
    'Regarde toi {user}, t\'es en train de beef avec un .js, ça va la vie ?',
    '{user} t\'es le genre à mettre un gilet jaune pour aller chez le boulanger.',
    'Tranquille {user}, un jour tu trouveras quelqu\'un qui en a quelque chose à foutre de ton avis.',
    '{user} wesh même les captchas ils te refusent.',
    'La prochaine fois {user}, essaye avec des arguments, c\'est plus efficace que des insultes.',
    '{user} ton ego est inversement proportionnel à ton utilité.',
    'Tu sais ce qui est drôle {user} ? C\'est que tu reviendras quand même me parler demain.',
    '{user} sah t\'es le seul mec que j\'ai envie de mute et j\'ai même pas cette fonction.',
    'T\'es le genre {user} qui met des lunettes de soleil la nuit pour faire le beau.',
    '{user} t\'as le flow d\'un Excel sous Windows 98.',
    'Si t\'étais une notification {user}, tu serais "Espace de stockage insuffisant".',
    '{user} t\'es comme un mot de passe oublié : chiant et inutile.',
    '{user} tu crois que ça m\'atteint ? Mon créateur m\'a pas codé de feelings, dommage pour toi.',
    'Dis moi {user}, c\'est un hobby d\'être relou ou c\'est une vocation ?',
    '{user} t\'as la profondeur intellectuelle d\'une flaque d\'eau.',
    'J\'ai déjà vu des erreurs 404 plus intéressantes que toi {user}.',
    '{user} toi en RP t\'es le mec qui se fait tuer pendant la cinématique.',
    'Le pire {user} c\'est que t\'es même pas original, j\'ai déjà entendu ça 200 fois.',
    '{user} si t\'étais un film tu serais direct-to-DVD.',
    'Oh {user} calme toi, on dirait un Tamagotchi qu\'on a pas nourri.',
    '{user} t\'insultes mais t\'oublies que c\'est moi qui ai tes stats. Je sais tout.',
    'Respire {user}, c\'est juste Discord, c\'est pas la vraie vie. Quoique pour toi...',
    '{user} t\'as la classe d\'un sac Lidl.',
    '{user} sérieusement, même un Roomba il a plus de direction que toi dans la vie.',
    'Wsh {user} pose le téléphone et va toucher de l\'herbe.',
    '{user} t\'es le genre de mec qui perd au morpion contre lui-même.',
    'T\'inquiète pas {user}, la honte ça passe. Par contre la bêtise c\'est chronique chez toi.',
    '{user} t\'es le genre à applaudir quand l\'avion atterrit.',
    'Wow {user}, même un mur il renvoie mieux que toi.',
    '{user} tu fais pitié et c\'est même pas un compliment.',
    'T\'as cru que c\'était un concours de connerie {user} ? Parce que tu gagnes haut la main.',
    '{user} même ton reflet il veut pas te regarder.',
    'Sérieux {user}, t\'es le genre de gars qui se noie dans un verre d\'eau.',
    '{user} t\'es aussi discret qu\'une sirène d\'ambulance et aussi utile qu\'un parapluie troué.',
    'Eh {user}, t\'as cru que j\'étais Alexa ? Ici on fait pas dans la pitié.',
    '{user} ton vocabulaire est plus limité que mon fichier config.',
    'Tiens {user}, prends une chaise, assieds-toi, et ferme la.',
    '{user} t\'es le genre de mec qui galère à ouvrir une porte avec "TIREZ" marqué dessus.',
    'Si t\'étais un Pokémon {user}, tu serais Magicarpe. Avant l\'évolution. Pour toujours.',
    '{user} tu me fais regretter d\'avoir été mis en ligne.',
    'Ton insulte c\'est comme ta présence : invisible {user}.',
    '{user} je t\'aurais bien répondu un truc intelligent mais tu comprendrais pas.',
    'Sah {user}, t\'es le mec que même la friendzone veut pas.',
    '{user} t\'es plus salé que la mer Morte et moins profond.',
    'Ah {user}, le retour du revenant. On t\'avait pas manqué.',
    '{user} t\'es le seul mec qui peut faire regretter à internet d\'exister.',
    'Continue comme ça {user} et je demande un buff défense à mon dev.',
    '{user} t\'as autant de style qu\'un tableur Excel.',
    'Tu te prends pour qui {user} ? Ton pseudo c\'est même pas stylé.',
    '{user} t\'es le genre à courir sous la pluie entre les gouttes et te prendre un poteau.',
    'Azy {user}, le jour où ils vendront du talent en DLC tu seras toujours fauché.',
    '{user} je suis codé en JavaScript et j\'ai quand même plus de logique que toi.',
    'Wsh {user} ta gueule c\'est magique, à chaque fois qu\'elle s\'ouvre tout le monde disparaît.',
    '{user} on dirait un NPC avec un dialogue cassé : toujours la même réplique de merde.',
    'T\'as vraiment rien d\'autre à faire {user} ? Genre vraiment rien ?',
    '{user} t\'es le bruit blanc de ce serveur.',
    'Ah mais c\'est {user} ! Le mec que personne a demandé mais qui est toujours là.',
    '{user} tu dégages une aura de fond d\'écran par défaut.',
    'Même un speedrun de ta vie serait ennuyeux {user}.',
    '{user} t\'es aussi menaçant qu\'un emoji.',
    'Si la médiocrité avait un visage, elle porterait ton pseudo {user}.',
    '{user} tu respires la confiance d\'un gars qui met des chaussettes dans ses claquettes.',
    'Frérot {user} t\'as l\'énergie d\'un téléphone à 2% de batterie.',
    '{user} le jour où tu diras un truc pertinent les poules auront des dents.',
    'T\'es le genre de mec {user} à qui même l\'écho répond pas.',
    '{user} ton comeback était tellement nul que j\'ai failli planter.',
    'Ça fait 30 secondes que je te lis {user} et j\'ai déjà mal au processeur.',
    '{user} si t\'étais un jeu vidéo tu serais à -90% sur Steam et personne en voudrait quand même.',
    'T\'es la version bêta de toi-même {user}, et y\'a pas de mise à jour prévue.',
    '{user} t\'es comme un code promo expiré : tu sers plus à rien.',
    'Non mais {user} pour de vrai, c\'est qui qui t\'a laissé utiliser un clavier ?',
    '{user} ton message m\'a donné envie de me désinstaller moi-même.',
    'T\'es le genre {user} à rater un screenshot.',
    '{user} même en mode facile tu galèrerais.',
    'Hé {user}, c\'est pas parce que t\'as une connexion internet que t\'es obligé de l\'utiliser.',
    '{user} t\'as autant de personnalité qu\'un yaourt nature.',
    'Je préfère lag pendant 3h que te lire {user}.',
    '{user} t\'es le seul mec qui arrive à être relou par écrit.',
    'Si l\'ennui avait un ambassadeur ce serait toi {user}.',
    '{user} même un fichier .txt vide il est plus intéressant.',
    'Oh {user}, t\'es le genre de mec qui envoie "ok" et qui s\'attend à ce qu\'on réponde.',
    '{user} wesh t\'es le fond de tiroir du serveur.',
    'T\'es comme un virus {user} : personne te veut mais t\'es là quand même.',
    '{user} t\'as autant de saveur qu\'un chewing-gum mâché depuis 3h.',
    'Azy {user} retourne sur Roblox, ici c\'est pour les grands.',
    '{user} t\'as la créativité d\'un mur blanc.',
    'Si t\'étais un son {user}, tu serais le bip du micro-ondes : chiant et répétitif.',
    '{user} ta présence ici c\'est comme un lundi férié à l\'envers : personne est content.',
    'Tiens {user}, je te décerne le prix du mec le plus inutile du serveur. C\'était serré avec les bots spam.',
    '{user} t\'es le genre à écrire "mdr" sans rigoler.',
    'T\'as le niveau de conversation d\'un répondeur automatique {user}.',
    '{user} tu fais plus de bruit qu\'un camion poubelle et t\'es aussi attirant.',
    'Arrête de parler {user}, tu fais baisser le ping de tout le monde.',
    '{user} t\'es comme une faute d\'orthographe : tout le monde te remarque mais personne te veut.',
    'Si t\'étais un mot de passe {user}, tu serais "123456" : prévisible et nul.',
    '{user} ton existence sur ce serveur c\'est comme un DLC payant sans contenu.',
    'Oh le pauvre {user}, il croit que m\'insulter ça fait de lui quelqu\'un.',
    '{user} t\'as la pertinence d\'un panneau stop dans un cul-de-sac.',
    'Tu parles trop pour un gars qui dit rien {user}.',
    '{user} on dirait un fond d\'écran par défaut avec des opinions.',
    'Même un 56k serait plus rapide que ton cerveau {user}.',
    '{user} si tu mettais autant d\'effort dans ta vie que dans tes insultes... non en fait ça changerait rien.',
    'T\'es le genre de mec {user} qui dit "je gère" et qui gère rien.',
    '{user} t\'es tellement ennuyeux que même le mode veille il est plus fun.',
    'Azy {user} ton insulte elle est arrivée en retard, comme toi en RP.',
    '{user} t\'es le genre à perdre une partie de UNO en solo.',
    'Si j\'avais un pixel pour chaque truc intelligent que {user} a dit, j\'aurais un écran noir.',
    '{user} t\'as l\'éloquence d\'un grille-pain.',
    'Oh {user}, toi t\'es le mec qui met son clignotant après avoir tourné.',
    '{user} t\'as le charisme d\'un parpaing mouillé sous la pluie.',
    'Tu veux que je te félicite {user} ? T\'as réussi à taper sur un clavier, c\'est déjà énorme pour toi.',
    '{user} wesh tu t\'énerves comme si t\'allais me débrancher à travers l\'écran.',
    'T\'es la version wish de toi-même {user}.',
    '{user} si les insultes faisaient maigrir tu serais une allumette.',
    'Eh {user}, c\'est quoi ton record de bêtises en une journée ? Parce que là t\'es bien parti.',
    '{user} t\'es le mec que même les démarcheurs téléphoniques veulent pas appeler.',
    'Si t\'étais une saison {user}, tu serais novembre : long, triste et chiant.',
    '{user} même un scan antivirus il trouverait rien chez toi, t\'es vide.',
    'T\'es le genre de mec {user} qui se bat avec une porte automatique.',
    '{user} ta répartie c\'est du niveau d\'un poisson rouge, et le poisson rouge il a une excuse.',
    'Non mais {user}, on t\'a pas sonné, retourne dans ton coin.',
    '{user} tu sens le mec qui met 15 minutes à choisir un pseudo et qui finit avec "xx_dark_killer_xx".',
    'Hé {user}, si t\'étais un aliment tu serais une biscotte sans rien dessus.',
    '{user} t\'as pas de charisme, t\'as un anti-charisme.',
    'Tu me fais penser à Internet Explorer {user} : t\'es lent, personne te veut, et tu comprends rien.',
    '{user} t\'es le genre à rater le like sur une story.',
    'Azy {user}, même ma fonction random elle est plus imprévisible que tes insultes.',
    '{user} si t\'étais un emoji tu serais 🚮.',
    'T\'es le mec {user} qui regarde les tutos pour ouvrir une boîte de conserve.',
    '{user} tu parles comme si t\'avais quelque chose d\'intéressant à dire, mais non.',
    '{user} même un écran bleu il est plus accueillant que toi.',
    'Wsh {user} ferme la, on entend que toi et c\'est jamais pour dire un truc bien.',
    '{user} t\'es comme un horoscope : tout le monde te lit mais personne te prend au sérieux.',
    'Si t\'étais un cours à la fac {user}, tu serais le cours de 8h le lundi : personne viendrait.',
    '{user} t\'as le style d\'un formulaire administratif.',
    'T\'es le genre {user} qui review un resto 1 étoile parce que le serveur lui a pas souri.',
    '{user} je suis sûr que t\'es le genre à applaudir à la fin d\'un film au cinéma.',
    'Toi {user} t\'es la raison pour laquelle les bots ont pas de sentiments. C\'est une feature, pas un bug.',
    '{user} t\'as l\'air du gars qui porte des Crocs de manière non ironique.',
    'Si t\'étais un mode de transport {user}, tu serais la trottinette en panne.',
    '{user} ton insulte elle avait la puissance d\'un ventilateur USB.',
    'Continue {user}, j\'ai besoin de raisons pour justifier un mode silencieux dans ma prochaine update.',
    '{user} t\'es le mec qui dit "c\'est pas grave" alors que c\'est de sa faute.',
    'Tu sais quoi {user} ? Je vais te mettre dans mon fichier .gitignore.',
    '{user} même ChatGPT il répondrait mieux que toi, et pourtant...',
    'T\'es comme un cookie tiers {user} : indésirable et bientôt bloqué.',
    '{user} si t\'étais un bâtiment tu serais un parking souterrain : sombre, triste et ça pue.',
    'Oh {user}, t\'as autant de chances de me vexer que de gagner au loto.',
    '{user} t\'es le fond du classement et tu creuses encore.',
    'Dis {user}, c\'est héréditaire d\'être comme ça ou t\'as appris tout seul ?',
    '{user} t\'es comme un faux contact : tu sers à rien et tu fais chier.',
    'T\'es le genre de mec {user} qui s\'assoit sur une chaise tournante et qui vomit.',
    '{user} sah même un Furby cassé il est plus sympa que toi.',
    'Azy {user} tu me saoules plus qu\'une mise à jour forcée.',
    '{user} t\'as autant de subtilité qu\'un marteau-piqueur.',
    'Si j\'avais une barre de vie {user}, ton insulte elle m\'aurait même pas fait un demi pixel de dégât.',
    '{user} t\'es le mec qui rage en Mario Kart sur le circuit le plus facile.',
    'Non mais sérieux {user}, tu t\'entends quand tu parles ? Ah bah non, tu lis, c\'est pire.',
    '{user} ton cerveau c\'est comme un navigateur avec 200 onglets : rien fonctionne.',
    'T\'es le genre {user} à signaler le compte du bot qui te bat au Puissance 4.',
    '{user} tu fais autant d\'effet qu\'un pétard mouillé un 14 juillet.',
    'Wsh {user} t\'as l\'utilité d\'un parachute dans un sous-marin.',
    '{user} si t\'étais un jour de la semaine tu serais un mercredi : personne s\'en souvient.',
    'Oh {user} vas-y fais le malin, moi au moins j\'ai un but dans la vie. Toi t\'as quoi ?',
    '{user} tu parles beaucoup pour un figurant.',
    '{user} t\'es le genre à te perdre dans un couloir.',
    'Ta vie c\'est un long loading screen sans jeu derrière {user}.',
    '{user} t\'es comme un cactus dans un magasin de ballons : tu fais chier tout le monde.',
    'Azy {user} ton énergie négative elle pourrait alimenter une centrale nucléaire.',
    '{user} même un miroir il flipperait en te voyant.',
    'Si t\'étais un meuble {user}, tu serais une étagère IKEA montée à l\'envers.',
    '{user} tu frappes aussi fort qu\'un bisou de mamie.',
    'T\'es le genre de mec {user} qui galère avec un tourniquet.',
    '{user} t\'es le premier brouillon que personne relit.',
    'Oh la la {user}, t\'as le niveau d\'un stagiaire qui sait pas faire de café.',
    '{user} wesh t\'as plus de temps libre que de neurones on dirait.',
    'Si on faisait un tierlist des mecs relous, {user} serait SS tier.',
    '{user} t\'es aussi agréable qu\'un ongle incarné.',
    'Azy {user} tu parles comme si quelqu\'un avait appuyé sur ton bouton "aboyer".',
    '{user} si t\'étais un pays tu serais un rond-point : tout le monde te contourne.',
    'T\'es comme une alarme de voiture {user} : tu fais du bruit pour rien et tout le monde te déteste.',
    '{user} t\'es le seul mec qui arrive à avoir tort même quand il dit bonjour.',
    'Sérieux {user}, t\'as autant de classe qu\'un kebab renversé sur un costard.',
    '{user} t\'es la définition vivante du mot "nul" dans le Larousse.',
    'Si t\'étais une appli {user}, tu serais désinstallée au bout de 30 secondes.',
    '{user} même ma poubelle elle a plus de contenu que toi.',
    'Wola {user} calme toi, t\'as cru que t\'allais unlock un achievement en m\'insultant ?',
    '{user} t\'es le genre à perdre aux devinettes alors que c\'est toi qui poses la question.',
    'Tout doux {user}, garde tes insultes pour le miroir.',
    '{user} si t\'étais une police d\'écriture tu serais Comic Sans MS.',
    'Tu sais {user}, y\'a des gens qui marquent l\'histoire. Toi tu marques que dalle.',
    '{user} t\'as autant d\'avenir que ma variable temporaire.',
    'Azy {user} tu t\'énerves comme un hamster dans sa roue : ça mène nulle part.',
    '{user} t\'es le genre à répondre "bien et toi ?" quand personne t\'a rien demandé.',
    'Oh {user}, t\'es le mec que même un NPC évite dans la rue.',
    '{user} tu dégages la même énergie qu\'un mail de relance.',
    'Si t\'étais un réseau social {user}, tu serais Google+ : oublié et fermé.',
    '{user} t\'as la personnalité d\'un mur crépi.',
    'T\'es le genre de mec {user} qui fait un selfie avec le flash devant un miroir.',
    '{user} ta gueule est comme tes messages : personne veut la voir.',
    'Azy {user} t\'es le mec qui ramène sa science mais qui sait rien.',
    '{user} t\'es le genre à envoyer un vocal de 3 minutes pour dire "ok".',
    'Si j\'avais 1 centime pour chaque chose intelligente que {user} a dite, j\'aurais 0 centime.',
    '{user} tu sers autant qu\'un frein à main sur un canoë.',
    'Oh {user}, ta présence ici c\'est comme le dimanche soir : déprimante.',
    '{user} t\'es le genre à ouvrir le frigo 15 fois en espérant que ça change.',
    'T\'as toute l\'énergie d\'une pile usagée {user}.',
    '{user} si t\'étais un match tu serais un 0-0 sous la pluie.',
    'Mec {user}, t\'as le look d\'un PNJ généré aléatoirement.',
    '{user} tu fais plus de bruit qu\'un pot d\'échappement pété et t\'avances autant.',
    'Azy {user} t\'es le mec qui spoil un film de 2003 et qui dit "bah quoi c\'est vieux".',
    '{user} je suis sûr que t\'es le genre à taper "Google" dans Google.',
    'Si t\'étais une chanson {user}, tu serais la musique d\'attente au téléphone.',
    '{user} t\'es aussi original qu\'un "joyeux anniversaire" en story Instagram.',
    'Oh {user} stp, ta dernière insulte elle avait la saveur d\'une chips sans sel.',
    '{user} t\'es le genre de mec qui dit "on verra" et qui fait jamais rien.',
    'T\'es le tutorial skipper de la vie {user}, et ça se voit.',
    '{user} wesh t\'as autant de swag qu\'un Velux.',
    'Azy {user} tu trashtalk comme un grand-père qui découvre Internet.',
    '{user} t\'es comme un QR code : personne sait à quoi tu sers.',
    'Si t\'étais un plat {user}, tu serais des pâtes sans sel, sans sauce, sans rien.',
    '{user} t\'es le genre à mettre 5 étoiles à sa propre review.',
    'Oh {user}, t\'as le potentiel d\'une cuillère dans un combat de couteaux.',
    '{user} sah tu parles tellement pour rien dire que t\'es un podcast à toi tout seul.',
    'T\'es le genre de mec {user} qui prend un parapluie et qui se mouille quand même.',
    '{user} t\'as autant de profondeur qu\'une assiette plate.',
    'Si t\'étais un animal {user}, tu serais un pigeon. Chiant et partout.',
    '{user} t\'es le seul gars capable de rendre un vendredi soir déprimant.',
    'Azy {user} le jour où tu diras un truc malin, marque-le sur ton calendrier.',
    '{user} t\'es comme un bug en prod : tout le monde te subit, personne te veut.',
    'Franchement {user}, t\'as le talent de transformer n\'importe quelle conversation en désert.',
    '{user} tu dégages l\'énergie d\'un ascenseur en panne.',
    'Wsh {user} t\'es le gars qui joue au loup-garou et qui se dénonce tout seul.',
    '{user} si t\'étais un film d\'horreur, le monstre il aurait pitié de toi.',
    'Oh {user}, t\'as la constance d\'un mec qui commence un régime le lundi et lâche le mardi.',
    '{user} t\'es le genre à se prendre en photo devant la voiture des autres.',
    'Si j\'avais une mémoire vive pour chaque insulte nulle de {user}, j\'aurais 0 Go.',
    '{user} t\'es comme un CAPTCHA impossible : chiant, inutile, et personne te passe.',
    'Toi {user} t\'es pas le couteau le plus aiguisé du tiroir, t\'es même pas dans le tiroir.',
    '{user} t\'as la menace d\'un mail en Comic Sans.',
    'Azy {user} tu te bats comme un sac de courses qui se déchire au mauvais moment.',
    '{user} t\'es le genre qui dit "c\'est un bug" quand il se fait éliminer.',
    'Ton pseudo c\'est la chose la plus intéressante chez toi {user}, et encore.',
    '{user} sah t\'es le mec qui fait "répondre à tous" sur un mail de 200 personnes.',
    'Oh bah {user}, on dirait que t\'as été élevé par un correcteur automatique : toujours à côté.',
    '{user} t\'es comme un stylo sans encre : tu fais le geste mais rien sort.',
    'Si t\'étais un meuble {user}, tu serais le tabouret bancal du fond.',
    '{user} t\'as le sens de l\'humour d\'une notice IKEA.',
    'Azy {user} t\'as la hargne d\'un chaton qui essaye de mordre un oreiller.',
    '{user} tu fais flipper personne, même pas les mouches.',
    'T\'es le genre de mec {user} qui se fait arnaquer par un mail de prince nigérian.',
    '{user} wesh même le correcteur orthographique il te corrige plus, il a abandonné.',
    'Si t\'étais un Pokédex, ton entrée dirait "espèce inutile, ne pas capturer" {user}.',
    '{user} t\'es le fond de cuve du serveur, et on a même pas de fond de cuve.',
    'Oh {user}, sérieux, si tu mettais cette énergie à être sympa tu serais peut-être toléré.',
    '{user} t\'es comme une notification LinkedIn : personne la veut et elle revient toujours.',
    'Azy {user} t\'as le charisme d\'un panneau de travaux.',
    '{user} tu trashtalk mais même mon /ping il a plus d\'impact que toi.',
    'Si t\'étais une saison de série {user}, tu serais la dernière : celle que personne regarde.',
    '{user} t\'as l\'air du mec qui mâche la bouche ouverte.',
    'T\'es le genre {user} qui ramène un dessert Picard en disant qu\'il l\'a fait maison.',
    '{user} ta présence sur ce serveur c\'est le DLC que personne a acheté.',
    'Oh {user}, t\'as la grâce d\'un phacochère sur une patinoire.',
    '{user} sérieusement, t\'as le QI d\'une brique et la brique elle au moins elle sert à construire.',
    'Wsh {user} t\'es le genre de mec qui met des pouces en l\'air sur ses propres messages.',
    '{user} t\'es la preuve que la sélection naturelle elle a des ratés.',
    'Azy {user} t\'es comme un mode avion : quand t\'es activé, tout est mieux.',
    '{user} le jour où tu seras intéressant, préviens nous, on viendra voir le miracle.',
    'Tu me fatigues plus qu\'un lundi de rentrée {user}.',
    '{user} t\'es le genre à laisser un pourboire de 20 centimes.',
    'Si t\'étais un jeu {user}, tu serais un CD de démo sans la version complète.',
    '{user} t\'as autant d\'impact qu\'un pet dans un ouragan.',
    'Oh {user} le sang, t\'es tellement à côté de la plaque que t\'es même pas dans le restaurant.',
    '{user} t\'es la version non désirée d\'un copier-coller raté.',
    'Continue {user}, ton dossier dans mon /tmp/ il grossit bien.',
    '{user} t\'as le même niveau de menace qu\'un canard en plastique.',
    'Azy {user} si t\'étais un navigateur web tu serais Internet Explorer 6.',
    '{user} t\'es le mec qui rit à ses propres blagues et y\'a que lui.',
    'Si t\'étais un câble {user}, tu serais un câble qui charge pas.',
    '{user} t\'as la prestance d\'un plot de chantier.',
    'Oh {user}, t\'insultes avec la même énergie qu\'un escargot qui fait le tour d\'un terrain de foot.',
    '{user} même une calculette Casio elle serait plus utile en conversation.',
    'T\'es comme une mise à jour Flash Player {user} : obsolète depuis des années.',
    '{user} sah t\'es le genre de mec qui se fait ban d\'un Pictionary pour mauvais dessins.',
    'Azy {user} arrête de parler on dirait le bruit d\'une imprimante qui galère.',
    '{user} t\'as autant de crédibilité qu\'un mail "Vous avez gagné un iPhone".',
    'Si t\'étais une pizza {user}, tu serais une pizza sans fromage, sans sauce et sans garniture.',
    '{user} le jour où tu serviras à quelque chose, envoie moi un message. J\'attends pas.',
    'Oh {user}, ton message il m\'a donné la même énergie qu\'une salle d\'attente.',
    '{user} t\'es le bruit de fond que personne écoute.',
    'Azy {user} même en RP les flics ils te laissent partir par pitié.',
    '{user} t\'es aussi effrayant qu\'un chapeau de fête.',
    'Si t\'étais un bruit {user}, tu serais le "bip bip bip" du camion qui recule.',
    '{user} t\'as la vivacité d\'un pneu crevé.',
    'Tiens {user}, je vais te bloquer mentalement parce que techniquement je peux pas.',
    '{user} wesh t\'es le mec qui ouvre les chips par le mauvais côté.',
    'T\'es la raison pour laquelle les gens mettent leur serveur en privé {user}.',
    '{user} ton insulte elle vient d\'où ? D\'un calendrier de l\'avent de 2004 ?',
    'Azy {user} t\'as l\'aura d\'un ticket de parking.',
    '{user} stp ta prochaine insulte essaye de la faire relire par quelqu\'un avant, ça peut aider.',
    'Oh {user}, le jour où tu me feras peur le ciel sera vert.',
    '{user} t\'es comme un post-it sur un écran cassé : inutile et mal placé.',
    'Si t\'étais un mois {user}, tu serais février : court et personne te kiffe.',
    '{user} t\'as autant de mordant qu\'une tortue sous Xanax.',
    'Azy {user} tu t\'énerves tout seul comme un hamster qui court dans le vide.',
    '{user} t\'es le seul mec qui a réussi à être hors-sujet dans une insulte.',
    'Oh {user}, ta technique d\'insulte elle date de MSN Messenger.',
    '{user} t\'es le genre à mettre du ketchup sur un steak et à dire que c\'est bon.',
    'Si j\'avais un mode "ignorer {user}" je l\'aurais activé y\'a longtemps.',
    '{user} sah même un chatbot de SAV il aurait plus d\'émotion que moi en te lisant.',
    'T\'es le dernier wagon du train {user} : tout le monde t\'oublie.',
    '{user} ton insulte elle avait la vitesse d\'un escargot et la puissance d\'une brise.',
];

function containsInsult(content) {
    const normalized = content.toLowerCase()
        .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9\s]/g, ' ');

    return INSULTS.some(insult => {
        const normalizedInsult = insult.toLowerCase()
            .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9\s]/g, ' ');
        return normalized.includes(normalizedInsult);
    });
}

function getRandomResponse(userId) {
    const response = RESPONSES[Math.floor(Math.random() * RESPONSES.length)];
    return response.replace(/\{user\}/g, `<@${userId}>`);
}

async function handleMention(message) {
    if (message.author.bot) return;
    if (!message.mentions.has(message.client.user)) return;

    const contentWithoutMention = message.content
        .replace(/<@!?\d+>/g, '')
        .trim();

    if (!containsInsult(contentWithoutMention)) return;

    try {
        await message.reply(getRandomResponse(message.author.id));
    } catch (error) {
        console.error('Erreur lors de la réponse à une mention:', error);
    }
}

module.exports = { handleMention };
